
env = Environment()
env.Program(target="txdemo",
        LIBS = ['ftdi1','usb-1.0'], 
        source=['src/txdemo.c'])

env.Append(CFLAGS='-Wall')
env.Append(CPATH = ['/usr/local/include/',
                    '/usr/local/include/libusb-1.0',
                    '/usr/local/include/libftdi1'])
env.Append(LIBPATH = ['/usr/local/lib/'])

